export enum Language {
  ZH_CN = "zh_CN",
  ZH_HK = "zh_HK",
  EN_US = "en_US",
}

export enum PageFeatureControl {
  HIDE_REMAINING_PAYMENT_TIME = "HIDE_REMAINING_PAYMENT_TIME",
  HIDE_ORDER_ITEM_DETAILS_BUTTON = "HIDE_ORDER_ITEM_DETAILS_BUTTON",
  HIDE_BIND_CARD_PAY_BUTTON = "HIDE_BIND_CARD_PAY_BUTTON",
  HIDE_EMAIL_ADDRESS = "HIDE_EMAIL_ADDRESS",
  HIDE_BILL_INFORMATION = "HIDE_BILL_INFORMATION",
}

export interface Headers {
  MerchantCode: string;
  NonceStr: string;
  Signature: string;
  Timestamp: string;
  Language: Language;
}

export enum ManagedOrderState {
  PENDING_PAYMENT = 1,
  PAID = 2,
  EXPIRED = 3,
  REFUNDED = 4,
  CLOSED = 5,
}

export enum Result {
  PENDING = 1,
  SUCCESSFULLY_PROCESSED = 2,
  PROCESSING_FAILED = 3,
  REFUNDED = 4,
  CANCELLED = 5,
  CLOSED = 6,
}

export enum OrderState {
  PROCESSING = 1,
  ORDER_PLACED_SUCCESSFULLY = 2,
  CLOSED = 3,
}

export enum PaymentMethod {
  VISA = 1,
  MASTERCARD = 2,
  UNIONPAY = 3,
  WECHAT_PAY = 4,
  ALIPAY = 5,
  AMERICAN_EXPRESS = 6,
  DINERS_CLUB = 7,
  JCB = 8,
  UNIONPAY_QUICKPASS = 9,
  PAYME = 12,
}

export enum TransactionType {
  TIP_ADJUSTMENT = 1,
  CANCEL_TIP = 2,
  SALE = 3,
  PRE_AUTH = 4,
  PRE_AUTH_ADJUSTMENT = 5,
  PRE_AUTH_VOID = 6,
  AUTH_COMPLETED = 7,
  PRE_AUTH_VOID_COMPLETED = 8,
  COUPON_REDEMPTION = 9,
  COUPON_REVERSAL = 10,
  VOID = 11,
  REVERSAL = 12,
  REFUND = 13,
  BALANCE_INQUIRY = 14,
  ALIPAY_SCAN = 15,
  ALIPAY_REVERSE_SCAN = 16,
  ALIPAY_PAYMENT_WINDOW = 17,
  ALIPAY_WEBSITE_PAYMENT = 18,
  ALIPAY_APP_PAYMENT = 19,
  ALIPAY_H5_PAYMENT = 20,
  WECHAT_SCAN = 21,
  WECHAT_REVERSE_SCAN = 22,
  UNIONPAY_SCAN = 23,
  UNIONPAY_REVERSE_SCAN = 24,
  WECHAT_PUBLIC_ACCOUNT = 25,
  WECHAT_MINI_PROGRAM_PAYMENT = 26,
  WECHAT_PC_WEB_PAYMENT = 27,
  WECHAT_APP_PAYMENT = 28,
  WECHAT_H5_PAYMENT = 29,
  WECHAT_PUBLIC_ACCOUNT_SERVICE_PROVIDER = 30,
  ALIPAY_REFUND = 31,
  WECHAT_REFUND = 32,
  UNIONPAY_REFUND = 33,
  ALIPAY_VOID = 34,
  WECHAT_VOID = 35,
  UNIONPAY_VOID = 36,
  ACCOUNT_TOP_UP = 37,
  ACCOUNT_WITHDRAWAL = 38,
  CUSTOMER_EXCHANGE = 39,
  OVERPAYMENT_REGISTRATION = 40,
  UNDERPAYMENT_REGISTRATION = 41,
  DEBIT_ADJUSTMENT = 42,
  CREDIT_ADJUSTMENT = 43,
  ERROR_PAYMENT = 44,
  ERROR_PAYMENT_RECORDING = 45,
  PAYMENT_RECOVERY = 46,
  PAYMENT_RECOVERY_RECORDING = 47,
  CUSTOMER_OUTWARD_REMITTANCE = 48,
  CUSTOMER_INWARD_REMITTANCE = 49,
  FUND_TRANSFER = 50,
  FOREIGN_EXCHANGE = 51,
  EXCHANGE_GAIN_LOSS_REGISTRATION = 52,
  BANK_DEPOSIT_LEDGER_FLIP = 53,
  POS_MONTHLY_RENTAL = 54,
  MARGIN_RELEASE = 55,
  MARGIN_FREEZE = 56,
  CNP_SALE = 57,
  CNP_VOID = 58,
  CNP_PRE_AUTH = 59,
  CNP_PRE_AUTH_VOID = 60,
  CNP_PRE_AUTH_COMPLETED = 61,
  CNP_PRE_AUTH_VOID_COMPLETED = 62,
  CNP_REFUND = 63,
  EC_REVERSAL = 64,
  MOTO_SALE = 65,
  MOTO_VOID = 66,
  MOTO_REFUND = 67,
  TOKEN_SALE = 68,
  TOKEN_VOID = 69,
  TOKEN_REFUND = 70,
  PAYNOW_SCANCODE = 71,
  PAYNOW_RETURN = 72,
  OCTOPUS_PAYMENT = 73,
  OCTOPUS_WALLET_PAYMENT = 74,
  REFUND_VOID = 75,
  CHARGEBACK = 76,
  REPRESENTMENT = 77,
  TIP_COMPREHENSIVE_ADJUSTMENT = 78,
  INTERNAL_ADJUSTMENT = 79,
  ALIPAY_QR_CODE = 80,
  WECHAT_QR_CODE = 81,
  PAYME_SCAN = 82,
  PAYME_REVERSE_SCAN = 83,
  PAYME_REFUND = 84,
  CNP_PRE_AUTH_ADJUSTMENT = 100,
  CNP_PRE_AUTH_REFUND = 101,
}

export enum CardOrganization {
  VISA = 1,
  MASTERCARD = 2,
  AMERICAEXPRESS = 3,
  DINERSCLUB = 4,
  DISCOVER = 5,
  INTERAC = 6,
  CARTESBANCAIRES = 7,
  JCB = 8,
  CHINAUNIONPAY = 9,
}

export enum WalletType {
  ALIPAY_HK = "ALIPAY_HK",
  ALIPAY_CN = "ALIPAY_CN",
  WECHATPAY_HK = "WECHATPAY_HK",
  WECHATPAY_CN = "WECHATPAY_CN",
}

export interface SignatureParams {
  requestMethod: string;
  endPoints: string;
  timestamp: number;
  nonceStr: string;
  merchantCode: string;
  body: string;
}
